### ISSUE TITLE
Database Schema

### ISSUE THREAD

**Issue by linakherchi** [kevinsuboy/stri#2]
- [x] Contains correct datatypes
- [x] Contains appropriate constraints/details
    - [x] primary key
    - [x] not null
    - [x] unique
    - [x] indexed
    - [x] foreign key
- [x] Contains bullet points after the table that state which foreign keys will reference to which table, or references to the associations which will be made
  - [x] foreign key and table name are lowercased, snake_cased and `back_ticked`
- [x] Correctly formatted
    - [x] schema is written in a table format
    - [x] the table's name are lowercased, snake_cased and `back_ticked`
    - [x] the table header column names are bolded
    - [x] columns names are lowercased and snaked_cased and `back_ticked`

**Comment by linakherchi** [comment]
1) Could you explain the `user_id` and `route_id` you have on the workouts table?

Please update the rest accordingly. 

Thanks !

**Comment by kevinsuboy** [comment]
The workout must belong to a user (i.e. September 7 morning jog), a workout may or may not belong to a route, which can be someone else's route. i.e. my September 7 morning jog can belong to Michael Phelps' "favorite San Francisco G street route"
